# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'vs2017-win2016'

steps:
# Azure file copy
# Copy files to Azure Blob Storage or virtual machines
- task: AzureFileCopy@3
  inputs:
    SourcePath: 'target/target/site/serenity'
    azureSubscription: 'AzCopy'
    Destination: 'AzureBlob'
    storage: 'practicepipelines'
    ContainerName: '$web'

