name: Deploy Node.js project to Azure Function App
on:
  [push]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   FUNCTION_DEPLOY
#   JF_ARTIFACTORY_1
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'azfun-odtapiac-ac'    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './NodeJS-Function/'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
      
    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v1.2.0
      env:
        JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_1 }}

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd
        
     #Create .zip
    - name: "Create ZIP"
      run: |
         Get-ChildItem $pwd | Compress-Archive -Destination ./backend.zip
      shell: pwsh   
     
    - name: "Upload to jfrog"
      run: |
        jfrog rt u "./backend.zip" Cairimia/practice
      shell: pwsh 
     
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.FUNCTION_DEPLOY }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
